search_tweets_api:
  account_type: "premium"
  endpoint: <"https://api.twitter.com/1.1/tweets/search/fullarchive/fullarchive/dev.json">
  consumer_key: "c11Wj0g6063k6YuBx6w7xVUX8"
  consumer_secret: "FweECqDNNdwPMWBQgDuC5F0Kbt8xcEtbaoCol5iYxSAqcfscPn"